# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-02 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2p', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('img', models.CharField(max_length=250)),
            ],
        ),
    ]
