# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f2p', '0003_farmdesciption_fruits_nutrientsveges'),
    ]

    operations = [
        migrations.CreateModel(
            name='registeredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=400)),
                ('contactNum', models.CharField(max_length=400)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f2p.Area')),
            ],
        ),
    ]
