# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f2p', '0004_registereduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('cost', models.FloatField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f2p.registeredUser')),
            ],
        ),
    ]
