# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2p', '0005_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='area',
        ),
        migrations.DeleteModel(
            name='orderDetails',
        ),
        migrations.DeleteModel(
            name='registeredUser',
        ),
    ]
