# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f2p', '0006_auto_20170909_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('cost', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='registeredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=400)),
                ('contactNum', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=250)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f2p.Area')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f2p.registeredUser'),
        ),
    ]
