# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2p', '0008_nutrientsfruits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='orderDetails',
        ),
    ]
