# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2p', '0010_auto_20170910_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmdesciption',
            name='veges_label',
        ),
        migrations.DeleteModel(
            name='farmDesciption',
        ),
    ]
