# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2p', '0012_farmdesciption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farmDesciption',
        ),
    ]
