# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2p', '0013_delete_farmdesciption'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmDesciption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('age', models.CharField(max_length=25)),
                ('contcNum', models.IntegerField()),
                ('land_owner', models.IntegerField()),
                ('area', models.CharField(max_length=250)),
                ('img', models.CharField(max_length=250)),
            ],
        ),
    ]
