# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f2p', '0014_farmdesciption'),
    ]

    operations = [
        migrations.CreateModel(
            name='fruitFarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f2p.farmDesciption')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f2p.Fruits')),
            ],
        ),
        migrations.CreateModel(
            name='vegeFarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f2p.farmDesciption')),
                ('vege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f2p.Veges')),
            ],
        ),
    ]
