# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2p', '0015_fruitfarm_vegefarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruitorder',
            name='fruit',
        ),
        migrations.RemoveField(
            model_name='fruitorder',
            name='orderID',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vegeorder',
            name='orderID',
        ),
        migrations.RemoveField(
            model_name='vegeorder',
            name='vege',
        ),
        migrations.DeleteModel(
            name='fruitOrder',
        ),
        migrations.DeleteModel(
            name='orderDetails',
        ),
        migrations.DeleteModel(
            name='vegeOrder',
        ),
    ]
